# Generated by Django 5.0.3 on 2024-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_importantclient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantclient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/media/'),
        ),
    ]
