# Generated by Django 5.0.3 on 2024-03-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_importantclient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantclient',
            name='image',
            field=models.ImageField(upload_to='clients/images/'),
        ),
    ]
