# Generated by Django 5.0.3 on 2024-03-27 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='package_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('coffee', 'Кафе'), ('milk', 'Мляко'), ('cocoa', 'Какао'), ('tea', 'Чай'), ('sweeteners', 'Подсладители'), ('cups', 'Чаши'), ('stirrers', 'Бъркалки'), ('extras', 'Допълнителни')], on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
    ]
