# Generated by Django 5.0.3 on 2024-04-11 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_intensity_product_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='intensity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
