# Generated by Django 5.0.3 on 2024-04-11 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='intensity',
        ),
        migrations.AddField(
            model_name='product',
            name='arabica',
            field=models.IntegerField(blank=True, help_text='Percentage of arabica content', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
