# Generated by Django 5.0.3 on 2024-04-11 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_intensity_product_arabica'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='robusta',
            field=models.IntegerField(blank=True, help_text='Percentage of arabica content', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
