# Generated by Django 5.0.3 on 2024-04-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='City',
        ),
    ]
